name: deploy
on: push

jobs:
  package:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: make package.zip
    - name: Push PreRelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: package.zip

  test-deploy:
    needs: package
    environment: Test
    runs-on: "ubuntu-latest"
    steps:
    - name: Sync trigger
      run: curl -sSf -HContent-Length:0 -XPOST "https://$APP_NAME.azurewebsites.net/admin/host/synctriggers?code=API_KEY"
      env:
        APP_NAME: ${{ secrets.AZURE_FUNCTION_NAME }}
        API_KEY: ${{ secrets.AZURE_FUNCTION_API_KEY }}
# vim:set ts=2 sw=2 sts=2:
