name: deploy
on: push

jobs:
  test-deploy:
    runs-on: "ubuntu-latest"
    environment: Test
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: go build -a -o app
      env:
        CGO_ENABLED: '0'
        GOOS: linux
        GOARCH: amd64
    - run: file app
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
# vim:set ts=2 sw=2 sts=2:
